import { OuvidoriaManifestacao } from '../../types';

export const DEMO_OUVIDORIA_MANIFESTACOES: OuvidoriaManifestacao[] = [
  {
    id: 'ouv-demo-1',
    protocolo: 'OUV-2026-0101',
    codigo_acesso: 'X8K2P',
    tipo: 'Reclamacao',
    assunto: 'Poste com lâmpada queimada há 2 semanas em frente à creche',
    descricao: 'A lâmpada do poste em frente à Creche Municipal Pequeno Príncipe está queimada há mais de 15 dias. À noite o local fica muito escuro, trazendo risco para pais, alunos e funcionários no encerramento das atividades.',
    bairro: 'Jardim Primavera',
    logradouro: 'Rua das Camélias, altura do nº 230',
    ponto_referencia: 'Em frente ao portão principal da Creche',
    privacidade: 'identificada',
    cidadao_nome: 'Marcos Vinícius Silva',
    cidadao_cpf: '042.***.***-18',
    cidadao_telefone: '(66) 99654-1230',
    cidadao_email: 'marcos.v.silva@email.com',
    status: 'Em Analise',
    prioridade: 'Alta',
    secretaria_sugerida: 'Obras, Pavimentação & Iluminação',
    secretaria_destino: 'Secretaria de Obras e Serviços Urbanos',
    data_manifestacao: new Date(Date.now() - 4 * 86400000).toISOString().split('T')[0],
    prazo_limite: new Date(Date.now() + 16 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'ouv-demo-2',
    protocolo: 'OUV-2026-0098',
    codigo_acesso: 'F9A1D',
    tipo: 'Elogio',
    assunto: 'Excelente atendimento da equipe de enfermagem da UBS Central',
    descricao: 'Gostaria de registrar meu elogio e profundo agradecimento à enfermeira Cláudia e toda equipe da UBS Central pelo atendimento carinhoso, ágil e atencioso com a minha mãe de 84 anos durante a vacinação.',
    bairro: 'Centro',
    logradouro: 'Avenida Brasil, 450',
    ponto_referencia: 'UBS Central Dr. Carlos Albuquerque',
    privacidade: 'identificada',
    cidadao_nome: 'Luciana Ferreira Borges',
    cidadao_cpf: '719.***.***-52',
    cidadao_telefone: '(66) 99877-4411',
    cidadao_email: 'luciana.borges@email.com',
    status: 'Respondida',
    prioridade: 'Normal',
    secretaria_sugerida: 'Saúde, Postos & Farmácia',
    secretaria_destino: 'Secretaria Municipal de Saúde',
    data_manifestacao: new Date(Date.now() - 10 * 86400000).toISOString().split('T')[0],
    prazo_limite: new Date(Date.now() + 10 * 86400000).toISOString(),
    resposta_oficial: 'Prezada Sra. Luciana, a Secretaria Municipal de Saúde agradece imensamente seu reconhecimento. Seu elogio foi compartilhado com a coordenação da UBS Central e anotado na pasta funcional dos servidores envolvidos. Agradecemos sua manifestação!',
    respondido_por: 'Ouvidoria Geral / Gabinete da Saúde',
    respondido_em: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'ouv-demo-3',
    protocolo: 'OUV-2026-0094',
    codigo_acesso: 'Z3M7C',
    tipo: 'Denuncia',
    assunto: 'Descarte clandestino de entulho e lixo tóxico em terreno baldio',
    descricao: 'Caminhões estão despejando restos de construção civil e tambores de solvente à noite em área de preservação próxima ao córrego. Risco iminente de contaminação e proliferação de vetores de dengue.',
    bairro: 'Vila Esperança',
    logradouro: 'Final da Rua Projetada 3, próximo ao bosque',
    ponto_referencia: 'Cerca de arame após a última casa',
    privacidade: 'sigilosa',
    cidadao_nome: 'Cidadão Residente (Identidade Protegida)',
    cidadao_cpf: '883.***.***-00',
    cidadao_telefone: '(66) 99201-9988',
    status: 'Encaminhada',
    prioridade: 'Urgente',
    secretaria_sugerida: 'Meio Ambiente & Limpeza',
    secretaria_destino: 'Secretaria de Meio Ambiente e Fiscalização de Posturas',
    data_manifestacao: new Date(Date.now() - 6 * 86400000).toISOString().split('T')[0],
    prazo_limite: new Date(Date.now() + 14 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: 'ouv-demo-4',
    protocolo: 'OUV-2026-0089',
    codigo_acesso: 'H4K9Q',
    tipo: 'Sugestao',
    assunto: 'Criação de faixa exclusiva para bicicletas nos finais de semana',
    descricao: 'Sugiro à Prefeitura implementar aos domingos e feriados uma ciclofaixa de lazer ao longo da Avenida dos Imigrantes, incentivando a prática esportiva segura e a convivência das famílias da nossa cidade.',
    bairro: 'Planalto',
    logradouro: 'Avenida dos Imigrantes',
    ponto_referencia: 'Extensão entre o Parque e o Centro',
    privacidade: 'identificada',
    cidadao_nome: 'Thiago de Almeida Costa',
    cidadao_cpf: '552.***.***-34',
    cidadao_telefone: '(66) 99712-3300',
    status: 'Nova',
    prioridade: 'Normal',
    secretaria_sugerida: 'Transportes & Estradas Rurais',
    secretaria_destino: 'Secretaria de Trânsito e Mobilidade Urbana',
    data_manifestacao: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
    prazo_limite: new Date(Date.now() + 19 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'ouv-demo-5',
    protocolo: 'OUV-2026-0075',
    codigo_acesso: 'T1N8B',
    tipo: 'Solicitacao',
    assunto: 'Operação tapa-buraco e cascalhamento na estrada vicinal do Assentamento',
    descricao: 'Devido às fortes chuvas recentes, formaram-se crateras profundas na estrada vicinal que liga a sede do município ao Assentamento São João, dificultando o escoamento de leite e o tráfego do ônibus escolar.',
    bairro: 'Zona Rural',
    logradouro: 'Estrada Vicinal Linha 4',
    ponto_referencia: 'Km 12, após a ponte de madeira',
    privacidade: 'anonima',
    cidadao_nome: 'Anônimo',
    status: 'Prorrogada',
    prioridade: 'Alta',
    secretaria_sugerida: 'Transportes & Estradas Rurais',
    secretaria_destino: 'Secretaria de Infraestrutura e Obras Rurais',
    data_manifestacao: new Date(Date.now() - 18 * 86400000).toISOString().split('T')[0],
    prazo_limite: new Date(Date.now() + 8 * 86400000).toISOString(),
    prorrogado: true,
    justificativa_prorrogacao: 'Prorrogação de 10 dias necessária para conclusão da licitação emergencial de combustível para as máquinas patroladeiras.',
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
  }
];
